on: [push]
jobs:
  build-karabiner-rule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make OUTPUT=olauncher.json
      - run: cat olauncher.json
      - uses: actions/upload-artifact@v3
        with:
          name: olauncher.json
          path: olauncher.json
          if-no-files-found: error 
