on: [push]
jobs:
  build-karabiner-rule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ruby CreateLauncherModeTemplate.rb > rule.json
      - uses: actions/upload-artifact@v3
        with:
          path: rule.json